/**
 * Paul Felix
 * CEN-3024 - Software Development
 * 01/26/2024
 * Book.java
 * This class will define the object book, conforming of Title, Author, and an autogenerated ID.
 */

package LibraryManagementSystem;
import java.util.concurrent.atomic.AtomicInteger;

class Book {
    private static final AtomicInteger idGenerator = new AtomicInteger(1);

    private int book_Id;
    private String title;
    private String author;

    public Book(String title, String author) {
        this.book_Id = idGenerator.getAndIncrement();
        this.title = title;
        this.author = author;
    }

    public int getBook_Id() {
        return book_Id;
    }

    public String getTitle() {
        return title;
    }

    public String getAuthor() {
        return author;
    }

    @Override
    public String toString() {
        return "Book ID: " + book_Id + ", Title: " + title + ", Author: " + author;
    }
}
